metal:
  port: 67
  listenaddr: '0.0.0.0'
  interface: 'any'
  hardwareaddr: 'D8-5E-D3-81-EE-02'

server:
  subnet: '255.255.255.0'
  serveraddr: '10.10.1.40'
  gateway: '10.10.1.1'
  dns: '10.10.1.1'
  lease_len: 3000
  iprange: '10.10.1.1-10.10.1.250'
