metal:
  port: 67
  interface: 'any'
  hardwareaddr: '04:ea:56:aa:3a:25'

server:
  subnet: '255.255.255.0'
  gateway: '10.10.1.1'
  dns: '10.10.1.1'
  lease_len: 3000
  iprange: '10.10.1.1-10.10.1.250'
